/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// The value-added services available for purchase with a shipping service offering.
    /// </summary>
    [DataContract]
    public partial class AvailableValueAddedServiceGroup :  IEquatable<AvailableValueAddedServiceGroup>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailableValueAddedServiceGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AvailableValueAddedServiceGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailableValueAddedServiceGroup" /> class.
        /// </summary>
        /// <param name="groupId">The type of the value-added service group. (required).</param>
        /// <param name="groupDescription">The name of the value-added service group. (required).</param>
        /// <param name="isRequired">When true, one or more of the value-added services listed must be specified. (required).</param>
        /// <param name="valueAddedServices">A list of optional value-added services available for purchase with a shipping service offering..</param>
        public AvailableValueAddedServiceGroup(string groupId = default(string), string groupDescription = default(string), bool? isRequired = default(bool?), List<ValueAddedService> valueAddedServices = default(List<ValueAddedService>))
        {
            // to ensure "groupId" is required (not null)
            if (groupId == null)
            {
                throw new InvalidDataException("groupId is a required property for AvailableValueAddedServiceGroup and cannot be null");
            }
            else
            {
                this.GroupId = groupId;
            }
            // to ensure "groupDescription" is required (not null)
            if (groupDescription == null)
            {
                throw new InvalidDataException("groupDescription is a required property for AvailableValueAddedServiceGroup and cannot be null");
            }
            else
            {
                this.GroupDescription = groupDescription;
            }
            // to ensure "isRequired" is required (not null)
            if (isRequired == null)
            {
                throw new InvalidDataException("isRequired is a required property for AvailableValueAddedServiceGroup and cannot be null");
            }
            else
            {
                this.IsRequired = isRequired;
            }
            this.ValueAddedServices = valueAddedServices;
        }
        
        /// <summary>
        /// The type of the value-added service group.
        /// </summary>
        /// <value>The type of the value-added service group.</value>
        [DataMember(Name="groupId", EmitDefaultValue=false)]
        public string GroupId { get; set; }

        /// <summary>
        /// The name of the value-added service group.
        /// </summary>
        /// <value>The name of the value-added service group.</value>
        [DataMember(Name="groupDescription", EmitDefaultValue=false)]
        public string GroupDescription { get; set; }

        /// <summary>
        /// When true, one or more of the value-added services listed must be specified.
        /// </summary>
        /// <value>When true, one or more of the value-added services listed must be specified.</value>
        [DataMember(Name="isRequired", EmitDefaultValue=false)]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// A list of optional value-added services available for purchase with a shipping service offering.
        /// </summary>
        /// <value>A list of optional value-added services available for purchase with a shipping service offering.</value>
        [DataMember(Name="valueAddedServices", EmitDefaultValue=false)]
        public List<ValueAddedService> ValueAddedServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AvailableValueAddedServiceGroup {\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("  GroupDescription: ").Append(GroupDescription).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("  ValueAddedServices: ").Append(ValueAddedServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AvailableValueAddedServiceGroup);
        }

        /// <summary>
        /// Returns true if AvailableValueAddedServiceGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of AvailableValueAddedServiceGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AvailableValueAddedServiceGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GroupId == input.GroupId ||
                    (this.GroupId != null &&
                    this.GroupId.Equals(input.GroupId))
                ) && 
                (
                    this.GroupDescription == input.GroupDescription ||
                    (this.GroupDescription != null &&
                    this.GroupDescription.Equals(input.GroupDescription))
                ) && 
                (
                    this.IsRequired == input.IsRequired ||
                    (this.IsRequired != null &&
                    this.IsRequired.Equals(input.IsRequired))
                ) && 
                (
                    this.ValueAddedServices == input.ValueAddedServices ||
                    this.ValueAddedServices != null &&
                    this.ValueAddedServices.SequenceEqual(input.ValueAddedServices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GroupId != null)
                    hashCode = hashCode * 59 + this.GroupId.GetHashCode();
                if (this.GroupDescription != null)
                    hashCode = hashCode * 59 + this.GroupDescription.GetHashCode();
                if (this.IsRequired != null)
                    hashCode = hashCode * 59 + this.IsRequired.GetHashCode();
                if (this.ValueAddedServices != null)
                    hashCode = hashCode * 59 + this.ValueAddedServices.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
