/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// The request schema for the directPurchaseShipment operation. When the channel type is Amazon, the shipTo address is not required and will be ignored.
    /// </summary>
    [DataContract]
    public partial class DirectPurchaseRequest :  IEquatable<DirectPurchaseRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectPurchaseRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DirectPurchaseRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectPurchaseRequest" /> class.
        /// </summary>
        /// <param name="shipTo">The address where the shipment will be delivered. For vendor orders, shipTo information is pulled directly from the Amazon order..</param>
        /// <param name="shipFrom">The address where the package will be picked up..</param>
        /// <param name="returnTo">The address where the package will be returned if it cannot be delivered..</param>
        /// <param name="packages">packages.</param>
        /// <param name="channelDetails">channelDetails (required).</param>
        /// <param name="labelSpecifications">The document (label) specifications requested. The default label returned is PNG DPI 203 4x6 if no label specification is provided. Requesting an invalid file format results in a failure..</param>
        public DirectPurchaseRequest(Address shipTo = default(Address), Address shipFrom = default(Address), Address returnTo = default(Address), PackageList packages = default(PackageList), ChannelDetails channelDetails = default(ChannelDetails), RequestedDocumentSpecification labelSpecifications = default(RequestedDocumentSpecification))
        {
            // to ensure "channelDetails" is required (not null)
            if (channelDetails == null)
            {
                throw new InvalidDataException("channelDetails is a required property for DirectPurchaseRequest and cannot be null");
            }
            else
            {
                this.ChannelDetails = channelDetails;
            }
            this.ShipTo = shipTo;
            this.ShipFrom = shipFrom;
            this.ReturnTo = returnTo;
            this.Packages = packages;
            this.LabelSpecifications = labelSpecifications;
        }
        
        /// <summary>
        /// The address where the shipment will be delivered. For vendor orders, shipTo information is pulled directly from the Amazon order.
        /// </summary>
        /// <value>The address where the shipment will be delivered. For vendor orders, shipTo information is pulled directly from the Amazon order.</value>
        [DataMember(Name="shipTo", EmitDefaultValue=false)]
        public Address ShipTo { get; set; }

        /// <summary>
        /// The address where the package will be picked up.
        /// </summary>
        /// <value>The address where the package will be picked up.</value>
        [DataMember(Name="shipFrom", EmitDefaultValue=false)]
        public Address ShipFrom { get; set; }

        /// <summary>
        /// The address where the package will be returned if it cannot be delivered.
        /// </summary>
        /// <value>The address where the package will be returned if it cannot be delivered.</value>
        [DataMember(Name="returnTo", EmitDefaultValue=false)]
        public Address ReturnTo { get; set; }

        /// <summary>
        /// Gets or Sets Packages
        /// </summary>
        [DataMember(Name="packages", EmitDefaultValue=false)]
        public PackageList Packages { get; set; }

        /// <summary>
        /// Gets or Sets ChannelDetails
        /// </summary>
        [DataMember(Name="channelDetails", EmitDefaultValue=false)]
        public ChannelDetails ChannelDetails { get; set; }

        /// <summary>
        /// The document (label) specifications requested. The default label returned is PNG DPI 203 4x6 if no label specification is provided. Requesting an invalid file format results in a failure.
        /// </summary>
        /// <value>The document (label) specifications requested. The default label returned is PNG DPI 203 4x6 if no label specification is provided. Requesting an invalid file format results in a failure.</value>
        [DataMember(Name="labelSpecifications", EmitDefaultValue=false)]
        public RequestedDocumentSpecification LabelSpecifications { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DirectPurchaseRequest {\n");
            sb.Append("  ShipTo: ").Append(ShipTo).Append("\n");
            sb.Append("  ShipFrom: ").Append(ShipFrom).Append("\n");
            sb.Append("  ReturnTo: ").Append(ReturnTo).Append("\n");
            sb.Append("  Packages: ").Append(Packages).Append("\n");
            sb.Append("  ChannelDetails: ").Append(ChannelDetails).Append("\n");
            sb.Append("  LabelSpecifications: ").Append(LabelSpecifications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DirectPurchaseRequest);
        }

        /// <summary>
        /// Returns true if DirectPurchaseRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DirectPurchaseRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DirectPurchaseRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipTo == input.ShipTo ||
                    (this.ShipTo != null &&
                    this.ShipTo.Equals(input.ShipTo))
                ) && 
                (
                    this.ShipFrom == input.ShipFrom ||
                    (this.ShipFrom != null &&
                    this.ShipFrom.Equals(input.ShipFrom))
                ) && 
                (
                    this.ReturnTo == input.ReturnTo ||
                    (this.ReturnTo != null &&
                    this.ReturnTo.Equals(input.ReturnTo))
                ) && 
                (
                    this.Packages == input.Packages ||
                    (this.Packages != null &&
                    this.Packages.Equals(input.Packages))
                ) && 
                (
                    this.ChannelDetails == input.ChannelDetails ||
                    (this.ChannelDetails != null &&
                    this.ChannelDetails.Equals(input.ChannelDetails))
                ) && 
                (
                    this.LabelSpecifications == input.LabelSpecifications ||
                    (this.LabelSpecifications != null &&
                    this.LabelSpecifications.Equals(input.LabelSpecifications))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipTo != null)
                    hashCode = hashCode * 59 + this.ShipTo.GetHashCode();
                if (this.ShipFrom != null)
                    hashCode = hashCode * 59 + this.ShipFrom.GetHashCode();
                if (this.ReturnTo != null)
                    hashCode = hashCode * 59 + this.ReturnTo.GetHashCode();
                if (this.Packages != null)
                    hashCode = hashCode * 59 + this.Packages.GetHashCode();
                if (this.ChannelDetails != null)
                    hashCode = hashCode * 59 + this.ChannelDetails.GetHashCode();
                if (this.LabelSpecifications != null)
                    hashCode = hashCode * 59 + this.LabelSpecifications.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
