/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// Item identifiers for an item in a direct fulfillment shipment.
    /// </summary>
    [DataContract]
    public partial class DirectFulfillmentItemIdentifiers :  IEquatable<DirectFulfillmentItemIdentifiers>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectFulfillmentItemIdentifiers" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DirectFulfillmentItemIdentifiers() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DirectFulfillmentItemIdentifiers" /> class.
        /// </summary>
        /// <param name="lineItemID">A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated for direct fulfillment multi-piece shipments. It is required if a vendor wants to change the configuration of the packages in which the purchase order is shipped. (required).</param>
        /// <param name="pieceNumber">A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated if a single line item has multiple pieces. Defaults to 1..</param>
        public DirectFulfillmentItemIdentifiers(string lineItemID = default(string), string pieceNumber = default(string))
        {
            // to ensure "lineItemID" is required (not null)
            if (lineItemID == null)
            {
                throw new InvalidDataException("lineItemID is a required property for DirectFulfillmentItemIdentifiers and cannot be null");
            }
            else
            {
                this.LineItemID = lineItemID;
            }
            this.PieceNumber = pieceNumber;
        }
        
        /// <summary>
        /// A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated for direct fulfillment multi-piece shipments. It is required if a vendor wants to change the configuration of the packages in which the purchase order is shipped.
        /// </summary>
        /// <value>A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated for direct fulfillment multi-piece shipments. It is required if a vendor wants to change the configuration of the packages in which the purchase order is shipped.</value>
        [DataMember(Name="lineItemID", EmitDefaultValue=false)]
        public string LineItemID { get; set; }

        /// <summary>
        /// A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated if a single line item has multiple pieces. Defaults to 1.
        /// </summary>
        /// <value>A unique identifier for an item provided by the client for a direct fulfillment shipment. This is only populated if a single line item has multiple pieces. Defaults to 1.</value>
        [DataMember(Name="pieceNumber", EmitDefaultValue=false)]
        public string PieceNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DirectFulfillmentItemIdentifiers {\n");
            sb.Append("  LineItemID: ").Append(LineItemID).Append("\n");
            sb.Append("  PieceNumber: ").Append(PieceNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DirectFulfillmentItemIdentifiers);
        }

        /// <summary>
        /// Returns true if DirectFulfillmentItemIdentifiers instances are equal
        /// </summary>
        /// <param name="input">Instance of DirectFulfillmentItemIdentifiers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DirectFulfillmentItemIdentifiers input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LineItemID == input.LineItemID ||
                    (this.LineItemID != null &&
                    this.LineItemID.Equals(input.LineItemID))
                ) && 
                (
                    this.PieceNumber == input.PieceNumber ||
                    (this.PieceNumber != null &&
                    this.PieceNumber.Equals(input.PieceNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LineItemID != null)
                    hashCode = hashCode * 59 + this.LineItemID.GetHashCode();
                if (this.PieceNumber != null)
                    hashCode = hashCode * 59 + this.PieceNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
