/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// The payload for the getShipmentDocuments operation.
    /// </summary>
    [DataContract]
    public partial class GetShipmentDocumentsResult :  IEquatable<GetShipmentDocumentsResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetShipmentDocumentsResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetShipmentDocumentsResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetShipmentDocumentsResult" /> class.
        /// </summary>
        /// <param name="shipmentId">shipmentId (required).</param>
        /// <param name="packageDocumentDetail">packageDocumentDetail (required).</param>
        public GetShipmentDocumentsResult(ShipmentId shipmentId = default(ShipmentId), PackageDocumentDetail packageDocumentDetail = default(PackageDocumentDetail))
        {
            // to ensure "shipmentId" is required (not null)
            if (shipmentId == null)
            {
                throw new InvalidDataException("shipmentId is a required property for GetShipmentDocumentsResult and cannot be null");
            }
            else
            {
                this.ShipmentId = shipmentId;
            }
            // to ensure "packageDocumentDetail" is required (not null)
            if (packageDocumentDetail == null)
            {
                throw new InvalidDataException("packageDocumentDetail is a required property for GetShipmentDocumentsResult and cannot be null");
            }
            else
            {
                this.PackageDocumentDetail = packageDocumentDetail;
            }
        }
        
        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name="shipmentId", EmitDefaultValue=false)]
        public ShipmentId ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets PackageDocumentDetail
        /// </summary>
        [DataMember(Name="packageDocumentDetail", EmitDefaultValue=false)]
        public PackageDocumentDetail PackageDocumentDetail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetShipmentDocumentsResult {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  PackageDocumentDetail: ").Append(PackageDocumentDetail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetShipmentDocumentsResult);
        }

        /// <summary>
        /// Returns true if GetShipmentDocumentsResult instances are equal
        /// </summary>
        /// <param name="input">Instance of GetShipmentDocumentsResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetShipmentDocumentsResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentId == input.ShipmentId ||
                    (this.ShipmentId != null &&
                    this.ShipmentId.Equals(input.ShipmentId))
                ) && 
                (
                    this.PackageDocumentDetail == input.PackageDocumentDetail ||
                    (this.PackageDocumentDetail != null &&
                    this.PackageDocumentDetail.Equals(input.PackageDocumentDetail))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentId != null)
                    hashCode = hashCode * 59 + this.ShipmentId.GetHashCode();
                if (this.PackageDocumentDetail != null)
                    hashCode = hashCode * 59 + this.PackageDocumentDetail.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
