/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// Reasons that make a shipment service offering ineligible.
    /// </summary>
    /// <value>Reasons that make a shipment service offering ineligible.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum IneligibilityReasonCode
    {
        
        /// <summary>
        /// Enum NOCOVERAGE for value: NO_COVERAGE
        /// </summary>
        [EnumMember(Value = "NO_COVERAGE")]
        NOCOVERAGE = 1,
        
        /// <summary>
        /// Enum PICKUPSLOTRESTRICTION for value: PICKUP_SLOT_RESTRICTION
        /// </summary>
        [EnumMember(Value = "PICKUP_SLOT_RESTRICTION")]
        PICKUPSLOTRESTRICTION = 2,
        
        /// <summary>
        /// Enum UNSUPPORTEDVAS for value: UNSUPPORTED_VAS
        /// </summary>
        [EnumMember(Value = "UNSUPPORTED_VAS")]
        UNSUPPORTEDVAS = 3,
        
        /// <summary>
        /// Enum VASCOMBINATIONRESTRICTION for value: VAS_COMBINATION_RESTRICTION
        /// </summary>
        [EnumMember(Value = "VAS_COMBINATION_RESTRICTION")]
        VASCOMBINATIONRESTRICTION = 4,
        
        /// <summary>
        /// Enum SIZERESTRICTIONS for value: SIZE_RESTRICTIONS
        /// </summary>
        [EnumMember(Value = "SIZE_RESTRICTIONS")]
        SIZERESTRICTIONS = 5,
        
        /// <summary>
        /// Enum WEIGHTRESTRICTIONS for value: WEIGHT_RESTRICTIONS
        /// </summary>
        [EnumMember(Value = "WEIGHT_RESTRICTIONS")]
        WEIGHTRESTRICTIONS = 6,
        
        /// <summary>
        /// Enum LATEDELIVERY for value: LATE_DELIVERY
        /// </summary>
        [EnumMember(Value = "LATE_DELIVERY")]
        LATEDELIVERY = 7,
        
        /// <summary>
        /// Enum PROGRAMCONSTRAINTS for value: PROGRAM_CONSTRAINTS
        /// </summary>
        [EnumMember(Value = "PROGRAM_CONSTRAINTS")]
        PROGRAMCONSTRAINTS = 8,
        
        /// <summary>
        /// Enum TERMSANDCONDITIONSNOTACCEPTED for value: TERMS_AND_CONDITIONS_NOT_ACCEPTED
        /// </summary>
        [EnumMember(Value = "TERMS_AND_CONDITIONS_NOT_ACCEPTED")]
        TERMSANDCONDITIONSNOTACCEPTED = 9,
        
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 10
    }

}
