/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// The payload for the purchaseShipment operation.
    /// </summary>
    [DataContract]
    public partial class PurchaseShipmentResult :  IEquatable<PurchaseShipmentResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseShipmentResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PurchaseShipmentResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseShipmentResult" /> class.
        /// </summary>
        /// <param name="shipmentId">shipmentId (required).</param>
        /// <param name="packageDocumentDetails">packageDocumentDetails (required).</param>
        /// <param name="promise">promise (required).</param>
        public PurchaseShipmentResult(ShipmentId shipmentId = default(ShipmentId), PackageDocumentDetailList packageDocumentDetails = default(PackageDocumentDetailList), Promise promise = default(Promise))
        {
            // to ensure "shipmentId" is required (not null)
            if (shipmentId == null)
            {
                throw new InvalidDataException("shipmentId is a required property for PurchaseShipmentResult and cannot be null");
            }
            else
            {
                this.ShipmentId = shipmentId;
            }
            // to ensure "packageDocumentDetails" is required (not null)
            if (packageDocumentDetails == null)
            {
                throw new InvalidDataException("packageDocumentDetails is a required property for PurchaseShipmentResult and cannot be null");
            }
            else
            {
                this.PackageDocumentDetails = packageDocumentDetails;
            }
            // to ensure "promise" is required (not null)
            if (promise == null)
            {
                throw new InvalidDataException("promise is a required property for PurchaseShipmentResult and cannot be null");
            }
            else
            {
                this.Promise = promise;
            }
        }
        
        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name="shipmentId", EmitDefaultValue=false)]
        public ShipmentId ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets PackageDocumentDetails
        /// </summary>
        [DataMember(Name="packageDocumentDetails", EmitDefaultValue=false)]
        public PackageDocumentDetailList PackageDocumentDetails { get; set; }

        /// <summary>
        /// Gets or Sets Promise
        /// </summary>
        [DataMember(Name="promise", EmitDefaultValue=false)]
        public Promise Promise { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseShipmentResult {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  PackageDocumentDetails: ").Append(PackageDocumentDetails).Append("\n");
            sb.Append("  Promise: ").Append(Promise).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PurchaseShipmentResult);
        }

        /// <summary>
        /// Returns true if PurchaseShipmentResult instances are equal
        /// </summary>
        /// <param name="input">Instance of PurchaseShipmentResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseShipmentResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentId == input.ShipmentId ||
                    (this.ShipmentId != null &&
                    this.ShipmentId.Equals(input.ShipmentId))
                ) && 
                (
                    this.PackageDocumentDetails == input.PackageDocumentDetails ||
                    (this.PackageDocumentDetails != null &&
                    this.PackageDocumentDetails.Equals(input.PackageDocumentDetails))
                ) && 
                (
                    this.Promise == input.Promise ||
                    (this.Promise != null &&
                    this.Promise.Equals(input.Promise))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentId != null)
                    hashCode = hashCode * 59 + this.ShipmentId.GetHashCode();
                if (this.PackageDocumentDetails != null)
                    hashCode = hashCode * 59 + this.PackageDocumentDetails.GetHashCode();
                if (this.Promise != null)
                    hashCode = hashCode * 59 + this.Promise.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
