/* 
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPI.Orders.Client.SwaggerDateConverter;

namespace Common.Models.Amzn.Shipping
{
    /// <summary>
    /// Indicates the tax specifications associated with the shipment for customs compliance purposes in certain regions.
    /// </summary>
    [DataContract]
    public partial class TaxDetail :  IEquatable<TaxDetail>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets TaxType
        /// </summary>
        [DataMember(Name="taxType", EmitDefaultValue=false)]
        public TaxType TaxType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaxDetail() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxDetail" /> class.
        /// </summary>
        /// <param name="taxType">taxType (required).</param>
        /// <param name="taxRegistrationNumber">The shipper&#39;s tax registration number associated with the shipment for customs compliance purposes in certain regions. (required).</param>
        public TaxDetail(TaxType taxType = default(TaxType), string taxRegistrationNumber = default(string))
        {
            // to ensure "taxType" is required (not null)
            if (taxType == null)
            {
                throw new InvalidDataException("taxType is a required property for TaxDetail and cannot be null");
            }
            else
            {
                this.TaxType = taxType;
            }
            // to ensure "taxRegistrationNumber" is required (not null)
            if (taxRegistrationNumber == null)
            {
                throw new InvalidDataException("taxRegistrationNumber is a required property for TaxDetail and cannot be null");
            }
            else
            {
                this.TaxRegistrationNumber = taxRegistrationNumber;
            }
        }
        

        /// <summary>
        /// The shipper&#39;s tax registration number associated with the shipment for customs compliance purposes in certain regions.
        /// </summary>
        /// <value>The shipper&#39;s tax registration number associated with the shipment for customs compliance purposes in certain regions.</value>
        [DataMember(Name="taxRegistrationNumber", EmitDefaultValue=false)]
        public string TaxRegistrationNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxDetail {\n");
            sb.Append("  TaxType: ").Append(TaxType).Append("\n");
            sb.Append("  TaxRegistrationNumber: ").Append(TaxRegistrationNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaxDetail);
        }

        /// <summary>
        /// Returns true if TaxDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of TaxDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaxDetail input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TaxType == input.TaxType ||
                    (this.TaxType != null &&
                    this.TaxType.Equals(input.TaxType))
                ) && 
                (
                    this.TaxRegistrationNumber == input.TaxRegistrationNumber ||
                    (this.TaxRegistrationNumber != null &&
                    this.TaxRegistrationNumber.Equals(input.TaxRegistrationNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaxType != null)
                    hashCode = hashCode * 59 + this.TaxType.GetHashCode();
                if (this.TaxRegistrationNumber != null)
                    hashCode = hashCode * 59 + this.TaxRegistrationNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
